
Get http://localhost:8000/user/getusername
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYzI1Mjk0ZWVhNTRkZjUwMGVhZmVlNyIsInVzZXJuYW1lIjoic2FzbGUiLCJpYXQiOjE2NDAxMjUxMTMsImV4cCI6MTY0MDIxMTUxM30.-rgrdBZRojMHMBxQYwEgoIHjXlIMBoGdkmtQGW-9jbA
###

Post http://localhost:8000/user/login
Content-Type: application/json

{
    "username": "le",
     "Password": "oar"
}

###

Post http://localhost:8000/user/create-user
Content-Type: application/json

{
    "username": "le",
    "FirstName": "farouk",
    "LastName":"SALEM",
     "PassportNumber": "546",
    "Email":"mail.com",
     "Password": "oar",
    "Age":"18",
     "Nationality": "Egyptian",
    "PhoneNumber":"0105233523"
}

###

GET http://localhost:8000/user/get-all-users