
Get http://localhost:8000/user/getusername
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYzcxODllNzMzNjdmNDZmNTdlZTMwMiIsInVzZXJuYW1lIjoic2FsZW0yNSIsImlhdCI6MTY0MDQ0NzY1OSwiZXhwIjoxNjQwNTM0MDU5fQ.uU5kJvqI8UMMK2TLKv8n3oO-oco8dzxXEs-Lk9fh4jc
###

Post http://localhost:8000/user/login
Content-Type: application/json

{
    "username": "salem25",
     "Password": "123"
}

###

Post http://localhost:8000/user/create-user
Content-Type: application/json

{
    "username": "asdm",
    "FirstName": "farouk",
    "LastName":"SALEM",
     "PassportNumber": "123",
    "Email":"oasdomoasd",
     "Password": "12",
    "Age":"18",
     "Nationality": "Egyptian",
    "PhoneNumber":"0105233523"
}

###

GET http://localhost:8000/user/get-all-users